update from lwa-antpos

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,19 +1,26 @@
 #!/bin/bash
-set -ex
-
-echo $HOSTNAME  # should be installing on calim
-echo $PWD  # should be base of code repo
-whoami  # should be user pipeline (or ubuntu?)
 
 # setup
+NAME="lwa-pyutils"
 DATE=$(date --iso-8601=seconds)
-LOG=~/deploy_lwa-pyutils_$DATE.log
+LOG=~/deploy_${NAME}_${DATE}.log
 
-if [[ $HOSTNAME =~ 'calim' ]]; then
-    echo "$DATE" >> $LOG 2>>$LOG
-    conda run -n datarecorder which python >> $LOG 2>>$LOG
-    conda run -n datarecorder git describe >> $LOG 2>>$LOG
-    conda run -n datarecorder pip install . >> $LOG 2>>$LOG
+set -ex >> $LOG 2>>$LOG
+
+rm ~/deploy_$NAME_*.log >> $LOG 2>>$LOG  # clean up old logs
+echo $HOSTNAME >> $LOG 2>>$LOG  # should be installing on calim
+echo $PWD >> $LOG 2>>$LOG  # should be base of code repo
+whoami >> $LOG 2>>$LOG  # should be user pipeline (or ubuntu?)
+
+if [[ $PWD =~ $NAME ]]; then
+    if [[ $HOSTNAME =~ 'calim' ]]; then
+	echo "$DATE" >> $LOG 2>>$LOG
+	conda run -n datarecorder which python >> $LOG 2>>$LOG
+	conda run -n datarecorder git describe >> $LOG 2>>$LOG
+	conda run -n datarecorder pip install . >> $LOG 2>>$LOG
+    else
+	echo "Not installing on this host" >> $LOG 2>>$LOG
+    fi
 else
-    echo "Not installing on this host"
+    echo "Not installing in this location" >> $LOG 2>>$LOG
 fi
